{{- if .Values.imagebuilder.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mira.name" . }}-image-builder
  labels:
    {{- include "mira.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.imagebuilder.replicaCount }}
  selector:
    matchLabels:
      {{- include "mira.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mira.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mira.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "mira.name" . }}-image-builder
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.imagebuilder.command | toYaml | nindent 12}}
          env:
          {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: image-builder
              containerPort: {{ .Values.imagebuilder.port }}
              protocol: TCP
          resources:
            {{- if .Values.imagebuilder.resources }}
            {{- toYaml .Values.imagebuilder.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}

---
{{- if .Values.imagebuilder.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mira.name" . }}-image-builder
  labels:
    {{- include "mira.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.imagebuilder.port }}
      targetPort: image-builder
      protocol: TCP
      name: image-builder
  selector:
    {{- include "mira.selectorLabels" . | nindent 4 }}
{{- end }}